### ISSUE TITLE
Ever considered puts()?

### ISSUE THREAD

**Issue by NicoNex** [holderekt/c-networking#1]
https://github.com/holderekt/c-networking/blob/169f05e1e3668756e06f46a359286c8fba3b0209/src/utils.h#L3

There's the function puts() in `stdio.h`. ;)

**Comment by holderekt** [comment]
Magari un giorno vorrò modificarla per farci qualcos'altro, in questo modo non dovrò modificare ogni pezzo di codice in cui la uso ma mi basterà modificare la funzione
